name: Trigger auto deployment for gossip-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/gossip-backend-AutoDeployTrigger-78bf2bde-9aca-43f8-91f6-c2419cb677cf.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GOSSIPBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GOSSIPBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GOSSIPBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: gossipbackend.azurecr.io
          registryUsername: ${{ secrets.GOSSIPBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GOSSIPBACKEND_REGISTRY_PASSWORD }}
          containerAppName: gossip-backend
          resourceGroup: Web-Forum
          imageToBuild: gossipbackend.azurecr.io/gossip-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


